# File docker-compose.yml

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "${BACK_API_PORT}:${BACK_API_PORT}"
    networks:
      - lion-d-atlas_network

networks:
  lion-d-atlas_network:
    driver: bridge
