# File docker-compose.yml

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        - BACK_API_PORT=${BACK_API_PORT}
        - BACK_MAIL_FROM=${BACK_MAIL_FROM}
        - BACK_EMAIL_PASS=${BACK_EMAIL_PASS}
    env_file:
      - .env
    ports:
      - "${BACK_API_PORT}:${BACK_API_PORT}"
    networks:
      - lionatals_network

networks:
  lionatals_network:
    driver: bridge
