name: Deployment
on:
  push:
    branches:
      - "main"
jobs:
  # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  # DockerHub
  # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build and Push Images to DockerHub
        run: |
      - name: Build and Push Images to DockerHub
        run: |
          echo "Building and pushing image for lion-d-atlas..."
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/lion-d-atlas:${GITHUB_SHA}" -f ./back/Dockerfile ./back
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/lion-d-atlas:${GITHUB_SHA}"


