name: Deployment
on:
  push:
    branches:
      - "main"
jobs:
  # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  # DockerHub
  # -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  push_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build and Push Images to DockerHub
        run: |
          app=Lion-d-Atlas
          echo "Building and pushing image for $app..."
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/$app:${GITHUB_SHA}" . && \
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/$app:${GITHUB_SHA}")

